# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: 冰码妞的小小窝
  params:
    description: 这里是冰码妞的个人博客，欢迎造访！
  menu:
    main:
      - name: 关于我
        url: '#about'
        weight: 10
      - name: 技能树
        url: '#skills'
        weight: 20
      - name: 经历
        url: '#experience'
        weight: 30
      - name: 专业技能
        url: '#accomplishments'
        weight: 40
      - name: 热点文章
        url: '#featured'
        weight: 50
      - name: 最近文章
        url: '#posts'
        weight: 60
      - name: 友情链接
        url: '#linkexchanges'
        weight: 70
      - name: 标签
        url: '#tags'
        weight: 80

# Additional languages
ja:
  languageCode: zh-Hans
  contentDir: content/ja
  title: 冰码妞的小小窝
  params:
    description: 这里是冰码妞的个人博客，欢迎造访！
  menu:
    main:
      - name: About
        url: '#about'
        weight: 10
      - name: Skills
        url: '#skills'
        weight: 20
      - name: Experience
        url: '#experience'
        weight: 30
      - name: Accomplishments
        url: '#accomplishments'
        weight: 40
      - name: Featured Posts
        url: '#featured'
        weight: 50
      - name: Recent Posts
        url: '#posts'
        weight: 60
      - name: Link Exchanges
        url: '#linkexchanges'
        weight: 70
      - name: Popular Topics
        url: '#tags'
        weight: 80
